### ISSUE TITLE
CI failures in torch19

### ISSUE THREAD

**Issue by asi1024** [pfnet/pytorch-pfn-extras#193]
- [x] test_tensorboard_writing (linux, win): #194
- [x] test_empty_shared_dataset (win): #194
- [x] test_transform[tuple-None-indices53-None-True] (linux): #194 
- [x] test_annotate (linux, win) #196
- [x] test_apply_annotation (linux, win) #196
- [x] test_scoped_anchor (linux, win) #197 
- [x] test_export_testcase (linux, win) #197
- [x] test_tensorboard_writer (linux, win): #194
- [x] test_queue_writer (linux): #194

linux: https://ci.preferred.jp/pytorch-pfn-extras.torch19-linux/73786/
win: https://ci.preferred.jp/pytorch-pfn-extras.torch19-win/73789/

**Comment by asi1024** [comment]
The UserWarning raise while importing `torch.utils.tensorboard` can be resolved by updating `setuptools` to the newest version.

**Comment by asi1024** [comment]
Now all CIs are green!
